# Softmax and Sigmoid

Task: more practice using the `softmax` function, and connect it with the `sigmoid` function.

## Setup

In [2]:
import torch
from torch import tensor
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
def softmax(x):
    return torch.softmax(x, axis=0)

## Task

Try this example:

In [4]:
x1 = tensor([0.1, 0.2, 0.3])
x2 = tensor([0.1, 0.2, 100])

In [5]:
softmax(x1)

tensor([0.3006, 0.3322, 0.3672])

1. Write a chunk of code that assigns `p = softmax(x1)` then evaluates `p.sum()`. **Before you run it**, predict what the output will be.

I think it will be the sums of each items in the tensor above. so 1 when calculated. 

In [6]:
p = softmax(x1)
p.sum()

tensor(1.0000)

2. Write a chunk of code that evaluates `p2 = softmax(x2)` and displays the result. **Before you run it**, predict what it will output.

By previewing the tensor value, we can see that first two values are way too small compared to the third tensor, so the value is going to be really close to 1, but not exactly 1.

In [7]:
display(softmax(x2))
p2 = softmax(x2)
p2.sum()

tensor([4.0638e-44, 4.4842e-44, 1.0000e+00])

tensor(1.)

3. Evaluate `torch.sigmoid(tensor(0.1))`. Write an expression that uses `softmax` to get the same output. *Hint*: Give `softmax` a two-element `tensor([num1, num2])`, where one of the numbers is 0.

In [8]:
print(f"{torch.sigmoid(tensor(0.1))=}")
softmax(torch.sigmoid(tensor([0.405, 0])))

torch.sigmoid(tensor(0.1))=tensor(0.5250)


tensor([0.5250, 0.4750])

## Analysis

1. A valid probability distribution has no negative numbers and sums to 1. Is `softmax(x)` a valid probability distribution? Why or why not?

Yes, softmax(x) will always have a valid probability as it transforms its input into probability distribution which sums up to 1. Function calculates the exponential of each element of x, and normalize the result by dividing each element by the sum of all element. 

2. Jargon alert: sometimes `x` is called the "logits" and `x.softmax(axis=0).log()` (or `x.log_softmax(axis=0)`) is called the "logprobs", short for "log probabilities". Complete the following expressions for `x1` (from the example above).

In [15]:
logits = x1
logprobs = x1.softmax(axis=0).log()
probabilities = x1.softmax(axis=0)
print(logits)
print(logprobs)
print(probabilities)
print(probabilities.sum())


tensor([0.1000, 0.2000, 0.3000])
tensor([-1.2019, -1.1019, -1.0019])
tensor([0.3006, 0.3322, 0.3672])
tensor(1.0000)


3. In light of your observations about the difference between `softmax(x1)` and `softmax(x2)`, why might `softmax` be an appropriate name for this function?

the name softmax captures the function's key properties of converting a set of numbers to probabilities that sum to 1, while also highlighting its smoothing effect on the input values.